export const APP_NAME = 'LibreLock'
export const API_BASE_URL = 'http://localhost:8000'
export const DB_NAME = 'librelock'
export const STORE = 'session'
export const KEY_ID = 'master_key'
export const SESSION_FLAG = 'vault_unlocked'
